name: PR Auto-approver
on:
  pull_request_target:
    branches:
      - "main"
    paths:
      - "_data/repositories.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
