name: Create PR on Issue

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  process_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install js-yaml
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/auto_core_adder/index.js')
            console.log(script({github, context}))
      - run: cat _data/repositories_new.yml
      - run: git add --all
      - run: git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
